name: Update

# on:
#   schedule:
#     - cron: '0 0 * * *'  # 每天午夜12点执行（UTC）

on:
  workflow_dispatch:

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: "Test"
          body: "Test"
        
          
