name: convert
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Github CLI
          run: |
            echo "xxxx" >> test.txt
            git config --local user.name "github-actions[bot]"
            git config --local user.email "actions@github.com"
            git add .
            git commit -m "test"
            git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push -f -u origin main




