name: Update

permissions:
  issues: write
  
on:
  workflow_dispatch:

jobs:
  update-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python Env
      - run: |
          python3 --version
