name: convert
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Github CLI
          run: |
            gh --version
            echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token  # 使用 GITHUB_TOKEN 进行认证



